2025-09-17 19:30:45.917110 - 404 Client Error: Not Found for url: https://myanimelist.net/anime/50159/Zombieland_Saga_Movie__Yumeginga_Paradise/episode
Traceback (most recent call last):
  File "C:\Users\gutor\OneDrive\Desktop\MAL Episode Rank\Site\main.py", line 90, in get_episodes_info
    response.raise_for_status()
  File "C:\Users\gutor\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://myanimelist.net/anime/50159/Zombieland_Saga_Movie__Yumeginga_Paradise/episode


2025-09-17 19:32:17.536712 - 404 Client Error: Not Found for url: https://myanimelist.net/anime/59192/Kimetsu_no_Yaiba_Movie_1__Mugenjou-hen_-_Akaza_Sairai/episode
Traceback (most recent call last):
  File "C:\Users\gutor\OneDrive\Desktop\MAL Episode Rank\Site\main.py", line 90, in get_episodes_info
    response.raise_for_status()
  File "C:\Users\gutor\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://myanimelist.net/anime/59192/Kimetsu_no_Yaiba_Movie_1__Mugenjou-hen_-_Akaza_Sairai/episode


2025-09-17 19:32:19.036424 - 404 Client Error: Not Found for url: https://myanimelist.net/anime/57555/Chainsaw_Man_Movie__Reze-hen/episode
Traceback (most recent call last):
  File "C:\Users\gutor\OneDrive\Desktop\MAL Episode Rank\Site\main.py", line 90, in get_episodes_info
    response.raise_for_status()
  File "C:\Users\gutor\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://myanimelist.net/anime/57555/Chainsaw_Man_Movie__Reze-hen/episode


2025-09-19 15:03:38.922224 - 404 Client Error: Not Found for url: https://myanimelist.net/anime/50159/Zombieland_Saga_Movie__Yumeginga_Paradise/episode
Traceback (most recent call last):
  File "C:\Users\gutor\OneDrive\Desktop\MAL Episode Rank\Site\main.py", line 56, in get_episodes_info
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\gutor\AppData\Roaming\Python\Python313\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://myanimelist.net/anime/50159/Zombieland_Saga_Movie__Yumeginga_Paradise/episode


2025-09-19 15:05:24.794810 - 404 Client Error: Not Found for url: https://myanimelist.net/anime/59192/Kimetsu_no_Yaiba_Movie_1__Mugenjou-hen_-_Akaza_Sairai/episode
Traceback (most recent call last):
  File "C:\Users\gutor\OneDrive\Desktop\MAL Episode Rank\Site\main.py", line 56, in get_episodes_info
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\gutor\AppData\Roaming\Python\Python313\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://myanimelist.net/anime/59192/Kimetsu_no_Yaiba_Movie_1__Mugenjou-hen_-_Akaza_Sairai/episode


2025-09-19 15:05:26.432429 - 404 Client Error: Not Found for url: https://myanimelist.net/anime/57555/Chainsaw_Man_Movie__Reze-hen/episode
Traceback (most recent call last):
  File "C:\Users\gutor\OneDrive\Desktop\MAL Episode Rank\Site\main.py", line 56, in get_episodes_info
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\gutor\AppData\Roaming\Python\Python313\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://myanimelist.net/anime/57555/Chainsaw_Man_Movie__Reze-hen/episode


2025-09-19 15:13:40.816609 - 404 Client Error: Not Found for url: https://myanimelist.net/anime/50159/Zombieland_Saga_Movie__Yumeginga_Paradise/episode
Traceback (most recent call last):
  File "C:\Users\gutor\OneDrive\Desktop\MAL Episode Rank\Site\main.py", line 56, in get_episodes_info
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\gutor\AppData\Roaming\Python\Python313\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://myanimelist.net/anime/50159/Zombieland_Saga_Movie__Yumeginga_Paradise/episode


2025-09-19 15:15:27.960415 - 404 Client Error: Not Found for url: https://myanimelist.net/anime/59192/Kimetsu_no_Yaiba_Movie_1__Mugenjou-hen_-_Akaza_Sairai/episode
Traceback (most recent call last):
  File "C:\Users\gutor\OneDrive\Desktop\MAL Episode Rank\Site\main.py", line 56, in get_episodes_info
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\gutor\AppData\Roaming\Python\Python313\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://myanimelist.net/anime/59192/Kimetsu_no_Yaiba_Movie_1__Mugenjou-hen_-_Akaza_Sairai/episode


2025-09-19 15:15:29.612834 - 404 Client Error: Not Found for url: https://myanimelist.net/anime/57555/Chainsaw_Man_Movie__Reze-hen/episode
Traceback (most recent call last):
  File "C:\Users\gutor\OneDrive\Desktop\MAL Episode Rank\Site\main.py", line 56, in get_episodes_info
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\gutor\AppData\Roaming\Python\Python313\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://myanimelist.net/anime/57555/Chainsaw_Man_Movie__Reze-hen/episode


2025-09-19 15:29:49.921036 - 404 Client Error: Not Found for url: https://myanimelist.net/anime/50159/Zombieland_Saga_Movie__Yumeginga_Paradise/episode
Traceback (most recent call last):
  File "C:\Users\gutor\OneDrive\Desktop\MAL Episode Rank\Site\main.py", line 56, in get_episodes_info
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\gutor\AppData\Roaming\Python\Python313\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://myanimelist.net/anime/50159/Zombieland_Saga_Movie__Yumeginga_Paradise/episode


2025-09-19 15:32:07.267580 - 404 Client Error: Not Found for url: https://myanimelist.net/anime/50159/Zombieland_Saga_Movie__Yumeginga_Paradise/episode
Traceback (most recent call last):
  File "C:\Users\gutor\OneDrive\Desktop\MAL Episode Rank\Site\main.py", line 56, in get_episodes_info
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\gutor\AppData\Roaming\Python\Python313\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://myanimelist.net/anime/50159/Zombieland_Saga_Movie__Yumeginga_Paradise/episode


2025-09-19 15:33:55.635695 - 404 Client Error: Not Found for url: https://myanimelist.net/anime/59192/Kimetsu_no_Yaiba_Movie_1__Mugenjou-hen_-_Akaza_Sairai/episode
Traceback (most recent call last):
  File "C:\Users\gutor\OneDrive\Desktop\MAL Episode Rank\Site\main.py", line 56, in get_episodes_info
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\gutor\AppData\Roaming\Python\Python313\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://myanimelist.net/anime/59192/Kimetsu_no_Yaiba_Movie_1__Mugenjou-hen_-_Akaza_Sairai/episode


2025-09-19 15:33:57.383915 - 404 Client Error: Not Found for url: https://myanimelist.net/anime/57555/Chainsaw_Man_Movie__Reze-hen/episode
Traceback (most recent call last):
  File "C:\Users\gutor\OneDrive\Desktop\MAL Episode Rank\Site\main.py", line 56, in get_episodes_info
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\gutor\AppData\Roaming\Python\Python313\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://myanimelist.net/anime/57555/Chainsaw_Man_Movie__Reze-hen/episode


2025-09-19 15:33:58.401392 - 'charmap' codec can't encode character '\u2705' in position 0: character maps to <undefined>
Traceback (most recent call last):
  File "C:\Users\gutor\OneDrive\Desktop\MAL Episode Rank\Site\main.py", line 110, in run_weekly_ranking
    print("✅ Ranking de episódios da semana gerado com sucesso!")
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python313\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 0: character maps to <undefined>


2025-09-19 15:34:43.193520 - 'charmap' codec can't encode character '\u2705' in position 0: character maps to <undefined>
Traceback (most recent call last):
  File "C:\Users\gutor\OneDrive\Desktop\MAL Episode Rank\Site\main.py", line 129, in run_anticipated_ranking
    print("✅ Ranking de animes mais esperados gerado com sucesso!")
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python313\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 0: character maps to <undefined>


2025-09-19 15:36:02.666254 - 404 Client Error: Not Found for url: https://myanimelist.net/anime/50159/Zombieland_Saga_Movie__Yumeginga_Paradise/episode
Traceback (most recent call last):
  File "C:\Users\gutor\OneDrive\Desktop\MAL Episode Rank\Site\main.py", line 56, in get_episodes_info
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\gutor\AppData\Roaming\Python\Python313\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://myanimelist.net/anime/50159/Zombieland_Saga_Movie__Yumeginga_Paradise/episode


2025-09-19 15:37:51.864493 - 404 Client Error: Not Found for url: https://myanimelist.net/anime/59192/Kimetsu_no_Yaiba_Movie_1__Mugenjou-hen_-_Akaza_Sairai/episode
Traceback (most recent call last):
  File "C:\Users\gutor\OneDrive\Desktop\MAL Episode Rank\Site\main.py", line 56, in get_episodes_info
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\gutor\AppData\Roaming\Python\Python313\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://myanimelist.net/anime/59192/Kimetsu_no_Yaiba_Movie_1__Mugenjou-hen_-_Akaza_Sairai/episode


2025-09-19 15:37:53.437180 - 404 Client Error: Not Found for url: https://myanimelist.net/anime/57555/Chainsaw_Man_Movie__Reze-hen/episode
Traceback (most recent call last):
  File "C:\Users\gutor\OneDrive\Desktop\MAL Episode Rank\Site\main.py", line 56, in get_episodes_info
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\gutor\AppData\Roaming\Python\Python313\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://myanimelist.net/anime/57555/Chainsaw_Man_Movie__Reze-hen/episode


2025-09-19 15:46:29.894829 - 404 Client Error: Not Found for url: https://myanimelist.net/anime/50159/Zombieland_Saga_Movie__Yumeginga_Paradise/episode
Traceback (most recent call last):
  File "C:\Users\gutor\OneDrive\Desktop\MAL Episode Rank\Site\main.py", line 56, in get_episodes_info
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\gutor\AppData\Roaming\Python\Python313\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://myanimelist.net/anime/50159/Zombieland_Saga_Movie__Yumeginga_Paradise/episode


2025-09-19 15:48:15.877064 - 404 Client Error: Not Found for url: https://myanimelist.net/anime/59192/Kimetsu_no_Yaiba_Movie_1__Mugenjou-hen_-_Akaza_Sairai/episode
Traceback (most recent call last):
  File "C:\Users\gutor\OneDrive\Desktop\MAL Episode Rank\Site\main.py", line 56, in get_episodes_info
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\gutor\AppData\Roaming\Python\Python313\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://myanimelist.net/anime/59192/Kimetsu_no_Yaiba_Movie_1__Mugenjou-hen_-_Akaza_Sairai/episode


2025-09-19 15:48:17.510682 - 404 Client Error: Not Found for url: https://myanimelist.net/anime/57555/Chainsaw_Man_Movie__Reze-hen/episode
Traceback (most recent call last):
  File "C:\Users\gutor\OneDrive\Desktop\MAL Episode Rank\Site\main.py", line 56, in get_episodes_info
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\gutor\AppData\Roaming\Python\Python313\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://myanimelist.net/anime/57555/Chainsaw_Man_Movie__Reze-hen/episode


2025-09-19 16:08:43.005237 - 404 Client Error: Not Found for url: https://myanimelist.net/anime/50159/Zombieland_Saga_Movie__Yumeginga_Paradise/episode
Traceback (most recent call last):
  File "C:\Users\gutor\OneDrive\Desktop\MAL Episode Rank\Site\main.py", line 56, in get_episodes_info
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\gutor\AppData\Roaming\Python\Python313\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://myanimelist.net/anime/50159/Zombieland_Saga_Movie__Yumeginga_Paradise/episode


2025-09-19 16:10:30.249865 - 404 Client Error: Not Found for url: https://myanimelist.net/anime/59192/Kimetsu_no_Yaiba_Movie_1__Mugenjou-hen_-_Akaza_Sairai/episode
Traceback (most recent call last):
  File "C:\Users\gutor\OneDrive\Desktop\MAL Episode Rank\Site\main.py", line 56, in get_episodes_info
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\gutor\AppData\Roaming\Python\Python313\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://myanimelist.net/anime/59192/Kimetsu_no_Yaiba_Movie_1__Mugenjou-hen_-_Akaza_Sairai/episode


2025-09-19 16:10:31.844133 - 404 Client Error: Not Found for url: https://myanimelist.net/anime/57555/Chainsaw_Man_Movie__Reze-hen/episode
Traceback (most recent call last):
  File "C:\Users\gutor\OneDrive\Desktop\MAL Episode Rank\Site\main.py", line 56, in get_episodes_info
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\gutor\AppData\Roaming\Python\Python313\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://myanimelist.net/anime/57555/Chainsaw_Man_Movie__Reze-hen/episode


2025-09-19 16:26:12.511471 - 404 Client Error: Not Found for url: https://myanimelist.net/anime/50159/Zombieland_Saga_Movie__Yumeginga_Paradise/episode
Traceback (most recent call last):
  File "C:\Users\gutor\OneDrive\Desktop\MAL Episode Rank\Site\main.py", line 56, in get_episodes_info
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\gutor\AppData\Roaming\Python\Python313\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://myanimelist.net/anime/50159/Zombieland_Saga_Movie__Yumeginga_Paradise/episode


2025-09-19 16:27:58.315918 - 404 Client Error: Not Found for url: https://myanimelist.net/anime/59192/Kimetsu_no_Yaiba_Movie_1__Mugenjou-hen_-_Akaza_Sairai/episode
Traceback (most recent call last):
  File "C:\Users\gutor\OneDrive\Desktop\MAL Episode Rank\Site\main.py", line 56, in get_episodes_info
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\gutor\AppData\Roaming\Python\Python313\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://myanimelist.net/anime/59192/Kimetsu_no_Yaiba_Movie_1__Mugenjou-hen_-_Akaza_Sairai/episode


2025-09-19 16:27:59.953969 - 404 Client Error: Not Found for url: https://myanimelist.net/anime/57555/Chainsaw_Man_Movie__Reze-hen/episode
Traceback (most recent call last):
  File "C:\Users\gutor\OneDrive\Desktop\MAL Episode Rank\Site\main.py", line 56, in get_episodes_info
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\gutor\AppData\Roaming\Python\Python313\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://myanimelist.net/anime/57555/Chainsaw_Man_Movie__Reze-hen/episode


2025-09-19 16:59:39.303327 - name 'get_season_anime_urls' is not defined
Traceback (most recent call last):
  File "C:\Users\gutor\OneDrive\Desktop\MAL Episode Rank\Site\main.py", line 25, in run_weekly_ranking
    anime_list = get_season_anime_urls()
                 ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'get_season_anime_urls' is not defined


2025-09-19 16:59:39.304347 - name 'scrape_anticipated_animes' is not defined
Traceback (most recent call last):
  File "C:\Users\gutor\OneDrive\Desktop\MAL Episode Rank\Site\main.py", line 58, in run_anticipated_ranking
    animes_data = scrape_anticipated_animes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'scrape_anticipated_animes' is not defined


2025-09-19 17:01:18.163751 - 404 Client Error: Not Found for url: https://myanimelist.net/anime/50159/Zombieland_Saga_Movie__Yumeginga_Paradise/episode
Traceback (most recent call last):
  File "C:\Users\gutor\OneDrive\Desktop\MAL Episode Rank\Site\main.py", line 56, in get_episodes_info
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\gutor\AppData\Roaming\Python\Python313\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://myanimelist.net/anime/50159/Zombieland_Saga_Movie__Yumeginga_Paradise/episode


2025-09-19 17:03:06.024515 - 404 Client Error: Not Found for url: https://myanimelist.net/anime/59192/Kimetsu_no_Yaiba_Movie_1__Mugenjou-hen_-_Akaza_Sairai/episode
Traceback (most recent call last):
  File "C:\Users\gutor\OneDrive\Desktop\MAL Episode Rank\Site\main.py", line 56, in get_episodes_info
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\gutor\AppData\Roaming\Python\Python313\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://myanimelist.net/anime/59192/Kimetsu_no_Yaiba_Movie_1__Mugenjou-hen_-_Akaza_Sairai/episode


2025-09-19 17:03:07.782902 - 404 Client Error: Not Found for url: https://myanimelist.net/anime/57555/Chainsaw_Man_Movie__Reze-hen/episode
Traceback (most recent call last):
  File "C:\Users\gutor\OneDrive\Desktop\MAL Episode Rank\Site\main.py", line 56, in get_episodes_info
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\gutor\AppData\Roaming\Python\Python313\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://myanimelist.net/anime/57555/Chainsaw_Man_Movie__Reze-hen/episode


2025-09-20 15:02:56.121705 - 404 Client Error: Not Found for url: https://myanimelist.net/anime/50159/Zombieland_Saga_Movie__Yumeginga_Paradise/episode
Traceback (most recent call last):
  File "C:\Users\gutor\OneDrive\Desktop\MAL Episode Rank\Site\main.py", line 80, in get_episodes_info
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\gutor\AppData\Roaming\Python\Python313\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://myanimelist.net/anime/50159/Zombieland_Saga_Movie__Yumeginga_Paradise/episode


